name: Test GitHub Actions on Ubuntu, macOS, and Windows

on: [pull_request, push]

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    name: Test with os ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Replace string in file
        uses: ./
        with:
          file: ./src/test.html
          old-string: %%WebChatValue1%%
          new-string: 'some env value'